import unittest
from spell_checker.correct_text import correction

incorrect_spellings = {
    "speling": "spelling",
    "ageg": "agege",
    "gbyi": "gbayi",
    "korrectud": "corrected",
    "ibiadn": "ibadan",
    "olidu": "olodo",
    "bycycle": "bicycle",
    "kirikiki": "kirikiri",
    "gbakaliki": "abakaliki",
    "inconvient": "inconvenient",
    "tnuu": "tinubu",
    "bhri": "buhari",
    "katsinah": "katsina",
    "unilg": "unilag",
    "peotry": "poetry",
    "olumoo": "oluomo",
    "peotryy": "poetry",
    "hsuxhpuppi": "hushpuppi",
    "olumooh": "oluomo",
    "adeboxe": "adeboye",
    "ixajaa": "ipaja",
    "abua": "abia",
    "adamwaa": "adamawa",
    "anamb": "anambra",
    "bauxhu": "bauchi",
    "benuet": "benue",
    "markufdi": "markudi",
    "bonroo": "borno",
    "mauguri": "maiduguri",
    "abasa": "asaba",
    "eboni": "ebonyi",
    "jiguwu": "jigawa",
    "kadn": "kaduna",
    "knoa": "kano",
    "lakija": "lokoja",
    "unilorien": "unilorin",
    "ekti": "ekiti",
    "oshoid": "oshodi",
    "akungba": "akungba",
    "oshogbyo": "oshogbo",
    "tarahat": "taraba",
    "jalio": "jalingo",
    "yobu": "yobe",
    "damatuur": "damaturu",
    "sba": "asaba",
    "yneogoa": "yenogoa",
    "owyerri": "owerri",
    "gaab": "agba",
    "unbin": "uniben",
    "danogte": "dangote",
    "otedeola": "otedola",
    "adenuugaa": "adenuga",
    "nogozii": "ngozi",
    "sahed": "saheed",
    "lekiky": "lekki",
    "ekosodun": "ekosodin",
    "nassarrawa": "nasarawa",
    "slejaa": "suleja",
    "dandaba": "dantata",
    "weik": "wike",
    "zieez": "azeez",
    "wizkdi": "wizkid",
    "marlhians": "marlians",
    "brymoho": "brymo",
    "dbnaj": "dbanj",
    "bbutunde": "babatunde",
    "baaburinde": "babarinde",
    "sidoq": "sodiq",
    "addeeji": "adedeji",
    "holadejii": "oladeji",
    "xeyii": "seyi",
    "olatunde": "olatunde",
    "oyedepo": "oyedepo",
    "emeka": "emeka",
    "chubuuke": "chibuike",
    "chibuzar": "chibuzor",
    "chdra": "chidera",
}

counter, length_spellings = 0, len(incorrect_spellings)
for spelling in incorrect_spellings:
    if correction(spelling) == incorrect_spellings[spelling]:
        counter += 1
    else:
        print(correction(spelling), incorrect_spellings[spelling])
print(
    f"The spell checker scored an accuracy of {round((counter/length_spellings)*100,3)}% on this test data"
)
